const palette = {
  blue: "var(--blue)",
  blueShade40: "var(--blue-shade-40)",
  blueShade20: "var(--blue-shade-20)",
  blueTint20: "var(--blue-tint-20)",
  blueTint90: "var(--blue-tint-90)",
  blueGreen: "var(--blue-green)",
  blueGreenShade40: "var(--blue-green-shade-40)",
  blueGreenShade20: "var(--blue-green-shade-20)",
  blueGreenTint20: "var(--blue-green-tint-20)",
  blueGreenTint90: "var(--blue-green-tint-90)",
  green: "var(--green)",
  greenShade40: "var(--green-shade-40)",
  greenShade20: "var(--green-shade-20)",
  greenTint20: "var(--green-tint-20)",
  greenTint90: "var(--green-tint-90)",
  yellowGreen: "var(--yellow-green)",
  yellowGreenShade40: "var(--yellow-green-shade-40)",
  yellowGreenShade20: "var(--yellow-green-shade-20)",
  yellowGreenTint20: "var(--yellow-green-tint-20)",
  yellowGreenTint90: "var(--yellow-green-tint-90)",
  yellow: "var(--yellow)",
  yellowShade40: "var(--yellow-shade-40)",
  yellowShade20: "var(--yellow-shade-20)",
  yellowTint20: "var(--yellow-tint-20)",
  yellowTint90: "var(--yellow-tint-90)",
  orange: "var(--orange)",
  orangeShade40: "var(--orange-shade-40)",
  orangeShade20: "var(--orange-shade-20)",
  orangeTint20: "var(--orange-tint-20)",
  orangeTint90: "var(--orange-tint-90)",
  red: "var(--red)",
  redShade40: "var(--red-shade-40)",
  redShade20: "var(--red-shade-20)",
  redTint20: "var(--red-tint-20)",
  redTint90: "var(--red-tint-90)",
  redViolet: "var(--red-violet)",
  redVioletShade40: "var(--red-violet-shade-40)",
  redVioletShade20: "var(--red-violet-shade-20)",
  redVioletTint20: "var(--red-violet-tint-20)",
  redVioletTint90: "var(--red-violet-tint-90)",
  violet: "var(--violet)",
  violetShade40: "var(--violet-shade-40)",
  violetShade20: "var(--violet-shade-20)",
  violetTint20: "var(--violet-tint-20)",
  violetTint90: "var(--violet-tint-90)",
  blueViolet: "var(--blue-violet)",
  blueVioletShade40: "var(--blue-violet-shade-40)",
  blueVioletShade20: "var(--blue-violet-shade-20)",
  blueVioletTint20: "var(--blue-violet-tint-20)",
  blueVioletTint90: "var(--blue-violet-tint-90)",
  black: "var(--black)",
  white: "var(--white)",
  blackTint10: "var(--black-tint-10)",
  blackTint20: "var(--black-tint-20)",
  blackTint40: "var(--black-tint-40)",
  blackTint70: "var(--black-tint-70)",
  blackTint90: "var(--black-tint-90)",
  blackTint95: "var(--black-tint-95)",
  blackTint97: "var(--black-tint-97)",

  hc0: "var(--hc-0)",
  hc1: "var(--hc-1)",
  hc2: "var(--hc-2)",
  hc3: "var(--hc-3)",
  hc4: "var(--hc-4)",
  hc5: "var(--hc-5)",

  transparent: "transparent",
};

const shadow = {
  1: [{ blur: 3, color: "rgba(1, 1, 1, 0.12)", y: 1 }],
  2: [
    { blur: 3, color: "rgba(1, 1, 1, 0.12)", y: 1 },
    { blur: 1, color: "rgba(1, 1, 1, 0.14)", y: 1 },
    { blur: 1, color: "rgba(1, 1, 1, 0.2)", y: 2 },
  ],
  3: [
    { blur: 8, color: "rgba(1, 1, 1, 0.12)", y: 1 },
    { blur: 4, color: "rgba(1, 1, 1, 0.14)", y: 3 },
  ],
  4: [
    { blur: 8, color: "rgba(1, 1, 1, 0.12)", y: 1 },
    { blur: 4, color: "rgba(1, 1, 1, 0.12)", y: 3 },
    { blur: 3, color: "rgba(1, 1, 1, 0.12)", y: 3 },
  ],
  5: [
    { blur: 18, color: "rgba(1, 1, 1, 0.12)", y: 1 },
    { blur: 10, color: "rgba(1, 1, 1, 0.14)", y: 6 },
  ],
};

const space = {
  1: 4,
  2: 8,
  3: 12,
  4: 16,
  5: 20,
  6: 24,
  7: 28,
  8: 32,
  9: 36,
  10: 40,
};

export { palette, shadow, space };
